# Generated by Django 2.1.4 on 2019-01-05 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kotha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kotha',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='kotha',
            name='content2',
        ),
    ]
