# Generated by Django 2.1.4 on 2019-01-05 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kotha', '0002_auto_20190105_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='kotha',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kotha',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kotha',
            name='content',
            field=models.CharField(max_length=240),
        ),
    ]
