# Generated by Django 2.1.4 on 2019-01-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kotha', '0004_kotha_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kotha',
            options={'ordering': ['-content']},
        ),
    ]
