# Generated by Django 2.1.4 on 2019-01-22 17:30

from django.db import migrations, models
import kotha.models


class Migration(migrations.Migration):

    dependencies = [
        ('kotha', '0006_auto_20190108_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kotha',
            options={},
        ),
        migrations.AlterField(
            model_name='kotha',
            name='content',
            field=models.CharField(max_length=240, validators=[kotha.models.validate_content]),
        ),
    ]
