# Generated by Django 2.2 on 2019-05-21 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kotha', '0007_auto_20190122_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kotha',
            options={'ordering': ['-timestamp', 'content']},
        ),
    ]
